FROM python:3.7

RUN apt-get update && \
    apt-get -y install \
        python3-pip \
        xvfb \
        ffmpeg \
        git \
        build-essential \
        cmake \
        zlib1g-dev \
        libbz2-dev \
        libpng-dev \
        libopencv-dev \
        libsdl2-dev 
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip install poetry --upgrade

RUN poetry install

COPY . .

RUN pip install -r requirements.txt

EXPOSE 54321

CMD [ "python", "-m", "./PongChannel.py" ]
